name: CICD

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: swiss-wowbagger
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Google Cloud Docker repo authentication
        run: gcloud auth configure-docker europe-west6-docker.pkg.dev --quiet

      - name: Build with Maven
        run: mvn -B -Pnative-shade clean verify

      - name: Push all Docker images
        if: github.ref == 'refs/heads/master'
        run: mvn -B docker:push

  deploy-wowbagger:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: swiss-wowbagger
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy swiss-wowbagger --image europe-west6-docker.pkg.dev/swiss-wowbagger/docker/swiss-wowbagger-jdk-server
          --region europe-west6 --max-instances=1 --ingress=all --allow-unauthenticated
          --port=7125 --memory=128Mi --args=-Xmx60m

  deploy-wowbagger-telegram:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: swiss-wowbagger
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy swiss-wowbagger-telegram --image europe-west6-docker.pkg.dev/swiss-wowbagger/docker/swiss-wowbagger-telegram
          --region europe-west6 --max-instances=1 --ingress=all --allow-unauthenticated
          --port=8080 --memory=128Mi --args=-Xmx60m
          --set-env-vars TOKEN=${{ secrets.TELEGRAM_TOKEN }},USER=${{ secrets.TELEGRAM_USER }}

  deploy-wowbagger-twitter:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: swiss-wowbagger
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to Cloud Run
        run: >
          gcloud run deploy swiss-wowbagger-twitter --image europe-west6-docker.pkg.dev/swiss-wowbagger/docker/swiss-wowbagger-twitter
          --region europe-west6 --max-instances=1 --ingress=all --allow-unauthenticated
          --port=8080 --memory=128Mi --args=-Xmx60m
          --set-env-vars CONSUMER_KEY=${{ secrets.TWITTER_BOT_CONSUMER_KEY }},CONSUMER_SECRET=${{ secrets.TWITTER_BOT_CONSUMER_SECRET }},ACCESS_TOKEN=${{ secrets.TWITTER_BOT_ACCESS_TOKEN }},ACCESS_SECRET=${{ secrets.TWITTER_BOT_ACCESS_SECRET }}
